import { preferenceEdits } from "./preferenceEdits";
import { PREFERENCE_EDIT_LIMIT } from "./settings";
import { questionFor } from "./prompts";
// Public game IDs and display names; session secrets are generated by the Next.js server.
const randomUUID = () => `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`;
const randomInt = (length: number) => Math.floor(Math.random() * length);
import { interpretShortPreferences, starterPreferences, validPreferences } from "./preferences";
import type { Preferences } from "./types";
import { scriptedDialogue } from "./dialogue";
import { CREATE_MS, FEEDBACK_MS, MESSAGE_LIMIT, PRESENCE_MS, REVEAL_MS, TURN_COUNT, TURN_MS, NPC_CREATE_MS, NPC_NAMES, NPC_PREFERENCES, PLAYER_NOUNS, NAME_LIMIT, courtSize } from "./settings";
import type { Room, RoomView } from "./types";

export function createRoom(capacity = 5, winnerSitsOut = false, ownerId: string | null = null): Room {
  return {
    minPlayers: null, maxPlayers: null, timersEnabled: true,
    capacity, winnerSitsOut, ownerId, advisorId: null,
    version: 1, id: randomUUID(), revision: 0, reign: 1, turn: 0, phase: "lobby", speaker: 0, deadline: null, turnStartedAt: 0,
    seats: NPC_NAMES.slice(0, courtSize(0, capacity)).map((npcName, i) => ({ id: `seat-${i}`, npcName, name: npcName, owner: null, total: 0 })),
    members: {}, preferences: starterPreferences(), lastRevealedPreference: null, creator: { name: "The founding council", memberId: null }, winner: null,
    submissions: {}, history: [], evaluation: null, creationPending: false, creationId: null, pausedAt: null
  };
}
export const turnKey = (room: Room) => `${room.id}:${room.reign}:${room.turn}`;
export class LobbyError extends Error {
  constructor(message: string, public status = 400) { super(message); }
}
const touch = (room: Room) => { room.revision++; };
function fitCourt(room: Room, now: number) {
  const humans = Object.entries(room.members).filter(([id, member]) => id !== room.advisorId && member.entered !== false && now - member.lastSeen <= PRESENCE_MS).length;
  const size = courtSize(humans, room.capacity ?? 5);
  while (room.seats.length < size && room.seats.length < NPC_NAMES.length) {
    const index = room.seats.length;
    room.seats.push({ id: `seat-${index}`, npcName: NPC_NAMES[index], name: NPC_NAMES[index], owner: null, total: 0 });
    touch(room);
  }
  while (room.seats.length > size && !room.seats[room.seats.length - 1].owner) {
    const removed = room.seats.pop();
    if (!removed) break;
    delete room.submissions[removed.id];
    for (const turn of room.history) delete turn[removed.id];
    if (room.speaker >= room.seats.length) room.speaker = Math.max(0, room.seats.length - 1);
    touch(room);
  }
}
function assignSeats(room: Room, now: number) {
  // Keep the evaluation roster fixed, but allow humans to inherit existing NPC seats.
  if (["lobby", "dialogue"].includes(room.phase)) fitCourt(room, now);
  for (const [id, member] of Object.entries(room.members).sort((a, b) => a[1].joinedAt - b[1].joinedAt)) {
    if (id === room.advisorId || member.entered === false || member.seatId || (member.misses ?? 0) >= 2 || now - member.lastSeen > PRESENCE_MS) continue;
    const seat = room.seats.find(s => !s.owner && !(room.winner?.seatId === s.id && ["reveal", "creating"].includes(room.phase)));
    if (!seat) continue;
    seat.owner = id; seat.name = member.name; member.seatId = seat.id; member.entered = true;
    // An unjudged NPC answer must not prevent its new human from answering.
    if (room.phase === "dialogue" && room.submissions[seat.id]?.by === null) delete room.submissions[seat.id];
    touch(room);
  }
}
export function join(room: Room, id: string, rawName: unknown, now: number) {
  if (typeof rawName !== "string" || !rawName.trim() || rawName.trim().length > NAME_LIMIT) throw new LobbyError(`Use a name of 1–${NAME_LIMIT} characters.`);
  const name = rawName.trim();
  if (Object.entries(room.members).some(([key, m]) => key !== id && now - m.lastSeen <= PRESENCE_MS && m.name.toLowerCase() === name.toLowerCase())) throw new LobbyError("That name is already at court. Try another.", 409);
  const previous = room.members[id];
  room.members[id] = { name, lastSeen: now, joinedAt: previous?.joinedAt ?? now, seatId: previous?.seatId ?? null, entered: previous?.entered ?? room.phase !== "lobby", ...(previous?.misses ? { misses: previous.misses } : {}) };
  const seat = room.seats.find(s => s.owner === id);
  if (seat) seat.name = name;
  assignSeats(room, now);
  touch(room);
}
export function heartbeat(room: Room, id: string | null, now: number) {
  if (id && room.members[id]) {
    room.members[id].lastSeen = now;
    assignSeats(room, now);
  }
}
export function resetCourt(room: Room, id: string, now: number) {
  const me = room.members[id];
  if (!me || now - me.lastSeen > PRESENCE_MS) throw new LobbyError("Join the court first.", 401);
  if (room.ownerId && room.ownerId !== id) throw new LobbyError("Only the admin can reset this lobby.", 403);
  const kept = { name: me.name, joinedAt: me.joinedAt };
  Object.assign(room, { ...createRoom(room.capacity, room.winnerSitsOut, room.ownerId), minPlayers: room.minPlayers ?? null, maxPlayers: room.maxPlayers ?? null, timersEnabled: room.timersEnabled !== false });
  room.members[id] = { name: kept.name, lastSeen: now, joinedAt: kept.joinedAt, seatId: null, entered: true, misses: 0 };
  assignSeats(room, now);
  touch(room);
}
export function enterCourt(room: Room, id: string, now: number) {
  const member = room.members[id];
  if (!member || now - member.lastSeen > PRESENCE_MS) throw new LobbyError("Join the court first.", 401);
  member.entered = true;
  member.misses = 0;
  assignSeats(room, now);
  if (room.timersEnabled !== false && room.phase === "dialogue" && seatedHumans(room, now) > 1 && room.deadline === null) {
    room.deadline = now + TURN_MS;
    touch(room);
  }
  if (room.phase !== "lobby") return;
  if (!room.seats.some(seat => seat.owner === id)) throw new LobbyError("The court is full.", 403);
  if (!room.ownerId && seatedHumans(room, now) >= (room.minPlayers ?? 1)) beginTurn(room, now);
}
export function startCourt(room: Room, id: string, now: number) {
  if (room.ownerId !== id) throw new LobbyError("Only the admin can start this lobby.", 403);
  if (room.phase !== "lobby") return;
  if (!room.members[id]?.seatId) throw new LobbyError("Take your seat first.");
  if (seatedHumans(room, now) < (room.minPlayers ?? 1)) throw new LobbyError("Waiting for the minimum number of players.");
  beginTurn(room, now);
}
export function closeIfAdminAbsent(room: Room, now: number) {
  if (room.closedAt != null) return true;
  if (!room.ownerId) return false;
  const admin = room.members[room.ownerId];
  if (admin && now - admin.lastSeen <= PRESENCE_MS) return false;
  room.closedAt = now;
  room.deadline = null;
  room.revision++;
  return true;
}
export function leave(room: Room, id: string, now: number) {
  const seat = room.seats.find(s => s.owner === id);
  if (seat) { seat.owner = null; seat.name = seat.npcName; }
  // Keep the winner identity until the creation deadline; only that session owns it.
  delete room.members[id]; assignSeats(room, now); touch(room);
}
function seatedHumans(room: Room, now: number) {
  return room.seats.filter(seat => seat.owner && room.members[seat.owner] && now - room.members[seat.owner].lastSeen <= PRESENCE_MS).length;
}
const solo = (room: Room, now: number) => seatedHumans(room, now) <= 1;
function phaseSpan(room: Room) {
  if (room.phase === "feedback") return FEEDBACK_MS;
  if (room.phase === "reveal") return REVEAL_MS;
  if (room.phase === "creating") return room.winner?.memberId ? CREATE_MS : NPC_CREATE_MS;
  return TURN_MS;
}
function winnerHere(room: Room, now: number) {
  const id = room.winner?.memberId;
  return !!id && !!room.members[id] && now - room.members[id].lastSeen <= PRESENCE_MS && ["reveal", "creating"].includes(room.phase);
}
function beginTurn(room: Room, now: number) {
  room.phase = "dialogue"; room.speaker = 0; room.turnStartedAt = now;
  room.submissions = {}; room.evaluation = null;
  assignSeats(room, now);
  room.deadline = room.timersEnabled === false || solo(room, now) ? null : now + TURN_MS;
  touch(room);
}
function completeTurn(room: Room, now: number) {
  for (const seat of room.seats) {
    if (!room.submissions[seat.id]) room.submissions[seat.id] = { ...scriptedDialogue("", room.preferences, room.turn), text: "", by: seat.owner, pending: false, mode: "scripted", timedOut: true, at: now };
    room.submissions[seat.id].pending = false;
    seat.total += room.submissions[seat.id].score;
  }
  room.history.push(structuredClone(room.submissions));
  retireQuietHumans(room);
  room.phase = "feedback"; room.deadline = room.timersEnabled === false ? null : now + FEEDBACK_MS; touch(room);
}
// Two silent rounds in a row return the seat to its NPC for the rest of the reign.
function retireQuietHumans(room: Room) {
  const latest = room.history.at(-1);
  if (!latest) return;
  for (const seat of room.seats) {
    if (!seat.owner) continue;
    const member = room.members[seat.owner];
    if (!member) continue;
    const entry = latest[seat.id];
    const spoke = !!entry && entry.by === seat.owner && !entry.timedOut && !!entry.text.trim();
    member.misses = spoke ? 0 : (member.misses ?? 0) + 1;
    if (member.misses < 2) continue;
    member.seatId = null;
    seat.owner = null;
    seat.name = seat.npcName;
  }
}
function reveal(room: Room, now: number) {
  const best = [...room.seats].sort((a, b) => b.total - a.total || room.submissions[b.id].score - room.submissions[a.id].score)[0];
  room.winner = { seatId: best.id, name: best.name, memberId: best.owner, total: best.total };
  room.phase = "reveal"; room.deadline = room.timersEnabled === false ? null : now + REVEAL_MS; touch(room);
}
export function nextPrincess(room: Room, preferences: Preferences, now: number) {
  if (room.phase !== "creating" || !room.winner || !validPreferences(preferences)) throw new LobbyError("The new princess cannot be created yet.", 409);
  if (preferenceEdits(room.preferences.prompt, preferences.prompt) > PREFERENCE_EDIT_LIMIT) throw new LobbyError(`You can change at most ${PREFERENCE_EDIT_LIMIT} characters.`);
  const winner = room.winner;
  // Preserve the winning identity in the lineage; the same player returns under a new name.
  room.creator = { name: winner.name, memberId: winner.memberId };
  const previousAdvisor = room.advisorId;
  room.advisorId = room.winnerSitsOut ? winner.memberId : null;
  if (previousAdvisor && previousAdvisor !== room.advisorId && room.members[previousAdvisor]) renamePlayer(room, previousAdvisor);
  if (winner.memberId && room.members[winner.memberId]) {
    if (room.winnerSitsOut) {
      const seat = room.seats.find(s => s.owner === winner.memberId);
      if (seat) { seat.owner = null; seat.name = seat.npcName; }
      room.members[winner.memberId].seatId = null;
    } else renamePlayer(room, winner.memberId);
  }
  room.lastRevealedPreference = room.preferences.prompt;
  room.preferences = structuredClone(preferences); room.reign++; room.turn = 0; room.winner = null;
  room.history = []; room.submissions = {}; room.creationPending = false; room.creationId = null;
  for (const seat of room.seats) seat.total = 0;
  for (const member of Object.values(room.members)) member.misses = 0;
  assignSeats(room, now); beginTurn(room, now);
}
export function defaultNextPrincess(room: Room, now: number) {
  // A timeout keeps the existing tastes. NPC changes obey the same edit budget.
  const candidate = room.winner?.memberId ? null : NPC_PREFERENCES
    .map((_, index) => NPC_PREFERENCES[(room.reign - 1 + index) % NPC_PREFERENCES.length])
    .find(prompt => preferenceEdits(room.preferences.prompt, prompt) <= PREFERENCE_EDIT_LIMIT);
  const preferences: Preferences = candidate
    ? { prompt: candidate, weights: interpretShortPreferences(candidate)!, source: "npc" }
    : { ...structuredClone(room.preferences), source: "npc" };
  nextPrincess(room, preferences, now);
}
export function advance(room: Room, now: number) {
  for (const seat of room.seats) {
    if (["lobby", "dialogue"].includes(room.phase) && seat.owner && (!room.members[seat.owner] || now - room.members[seat.owner].lastSeen > PRESENCE_MS)) {
      const member = room.members[seat.owner]; if (member) member.seatId = null;
      seat.owner = null; seat.name = seat.npcName; touch(room);
    }
  }
  // Expired identities are bounded; active creators/winners retain their identity.
  for (const [id, member] of Object.entries(room.members)) if (now - member.lastSeen > 86_400_000 && id !== room.creator.memberId && id !== room.winner?.memberId) delete room.members[id];
  assignSeats(room, now);
  if (room.phase === "lobby" || (room.timersEnabled === false && room.phase !== "evaluating")) return;
  const advisorHere = room.advisorId && room.members[room.advisorId] && now - room.members[room.advisorId].lastSeen <= PRESENCE_MS;
  const playing = seatedHumans(room, now) > 0 || winnerHere(room, now) || advisorHere;
  if (!playing) {
    if (room.pausedAt == null) { room.pausedAt = now; touch(room); }
    return;
  }
  if (room.deadline != null && now - room.deadline > phaseSpan(room)) {
    room.deadline = now + phaseSpan(room);
    room.pausedAt = null;
    touch(room);
  } else if (room.pausedAt != null) {
    if (room.deadline != null && room.deadline <= now) room.deadline = now + phaseSpan(room);
    room.pausedAt = null;
    touch(room);
  }
  if (room.phase === "dialogue") {
    if (solo(room, now)) room.deadline = null;
    else if (room.deadline === null) room.deadline = now + TURN_MS;
    if (room.deadline !== null && now >= room.deadline) {
      for (const seat of room.seats) if (seat.owner && !room.submissions[seat.id]) {
        room.submissions[seat.id] = { ...scriptedDialogue("", room.preferences, room.turn), text: "", by: seat.owner, pending: true, mode: "scripted", timedOut: true, at: now };
        touch(room);
      }
    }
  } else if (room.phase === "feedback" && now >= room.deadline!) {
    if (room.turn >= TURN_COUNT - 1) reveal(room, now);
    else { room.turn++; beginTurn(room, now); }
  } else if (room.phase === "reveal" && now >= room.deadline!) {
    room.phase = "creating"; room.deadline = now + (room.winner?.memberId ? CREATE_MS : NPC_CREATE_MS); touch(room);
  } else if (room.phase === "creating" && now >= room.deadline!) defaultNextPrincess(room, now);
}
export function setTimers(room: Room, enabled: boolean, now: number) {
  room.timersEnabled = enabled;
  if (room.phase !== "evaluating") {
    room.deadline = !enabled || ["lobby", "results"].includes(room.phase) || (room.phase === "dialogue" && solo(room, now)) ? null : now + phaseSpan(room);
    room.pausedAt = null;
  }
}
export function continueUntimed(room: Room, now: number) {
  if (room.timersEnabled !== false) return;
  if (room.phase === "feedback") {
    if (room.turn >= TURN_COUNT - 1) reveal(room, now);
    else { room.turn++; beginTurn(room, now); }
  } else if (room.phase === "reveal") {
    room.phase = "creating"; room.deadline = null; touch(room);
  } else if (room.phase === "creating" && !room.winner?.memberId) defaultNextPrincess(room, now);
}
export function nextSpeaker(room: Room, id: string, now: number) {
  if (!room.members[id] || now - room.members[id].lastSeen > PRESENCE_MS) throw new LobbyError("Join the court first.", 401);
  if (room.phase !== "results") throw new LobbyError("Wait for the court’s results.", 409);
  if (room.speaker === room.seats.length - 1) completeTurn(room, now);
  else { room.speaker++; room.submissions[room.seats[room.speaker].id].at = now; touch(room); }
}
function freshName(room: Room) {
  const used = new Set(Object.values(room.members).map(m => m.name.toLowerCase()));
  const available = PLAYER_NOUNS.filter(noun => !used.has(noun.toLowerCase()));
  const noun = available.length ? available[randomInt(available.length)] : PLAYER_NOUNS[randomInt(PLAYER_NOUNS.length)];
  let name = noun;
  for (let suffix = 2; used.has(name.toLowerCase()); suffix++) name = `${noun} ${suffix}`;
  return name;
}
function renamePlayer(room: Room, id: string) {
  const member = room.members[id];
  member.name = freshName(room);
  const seat = room.seats.find(s => s.owner === id);
  if (seat) seat.name = member.name;
  touch(room);
}
// Opening the page seats you; refreshing keeps the same name and seat.
export function ensureJoined(room: Room, id: string, now: number) {
  if (!room.members[id]) join(room, id, freshName(room), now);
  // Existing courts may still have a seated-out advisor from the old rule.
  if (room.advisorId !== id && room.creator.memberId === id && room.members[id].name === room.creator.name) renamePlayer(room, id);
  heartbeat(room, id, now);
}
export function submit(room: Room, id: string, key: unknown, value: unknown, now: number) {
  const seat = room.seats.find(s => s.owner === id);
  if (!seat) throw new LobbyError("You are watching this reign.", 403);
  if (room.phase !== "dialogue" || key !== turnKey(room) || (room.deadline !== null && now >= room.deadline)) throw new LobbyError("That turn has ended. Your next chance is coming.", 409);
  if (room.submissions[seat.id]) throw new LobbyError("Your message is already in.", 409);
  if (typeof value !== "string" || !value.trim() || value.length > MESSAGE_LIMIT) throw new LobbyError(`Write 1–${MESSAGE_LIMIT} characters.`);
  const text = value.trim();
  room.submissions[seat.id] = { ...scriptedDialogue(text, room.preferences, room.turn), text, by: id, pending: true, timedOut: false, mode: "scripted", at: now };
  touch(room); return seat.id;
}
const markOutOfTen = (score: number) => score > 0 ? Math.max(1, Math.min(10, Math.round(score / 10))) : null;
// Later turns count more: turn 1 ×1, turn 2 ×2, and so on. Result is 0–100.
function courtLog(room: Room) {
  const lines: Array<{ name: string; event: string; note: string | null; reply: string | null }> = [];
  room.history.forEach((turn, index) => {
    for (const seat of room.seats) {
      const spoken = turn[seat.id];
      if (!spoken) continue;
      const mark = markOutOfTen(spoken.score);
      const silent = spoken.timedOut || !spoken.text.trim();
      lines.push({
        name: seat.name,
        event: silent ? `said nothing on turn ${index + 1}.` : `spoke on turn ${index + 1}. ${mark ?? 0}/10.`,
        note: silent ? null : spoken.feedback,
        reply: silent ? null : spoken.reply,
      });
    }
  });
  if (room.winner) lines.push({ name: room.winner.name, event: "won the crown’s ear.", note: null, reply: null });
  return lines.slice(-10);
}
export function likedScore(scores: number[]) {
  let weighted = 0, weights = 0;
  scores.forEach((score, turn) => { const weight = turn + 1; weighted += score * weight; weights += weight; });
  return weights ? Math.max(0, Math.min(100, Math.round(weighted / weights))) : 0;
}
export function view(room: Room, id: string | null, now: number): RoomView {
  const member = id ? room.members[id] : null;
  const seat = room.seats.find(s => s.owner === id && id !== null);
  const own = seat ? room.submissions[seat.id] : null;
  const waiting = ["dialogue", "evaluating"].includes(room.phase);
  const dialogue = own && own.by === id ? { text: own.text, reply: waiting ? "" : own.reply, feedback: waiting ? "" : own.feedback, pending: own.pending, mode: own.mode, timedOut: own.timedOut } : null;
  return {
    closedAt: room.closedAt ?? null, privateLobby: !!room.ownerId,
    minPlayers: room.minPlayers ?? null, maxPlayers: room.maxPlayers ?? null, timersEnabled: room.timersEnabled !== false,
    capacity: room.capacity ?? 5, winnerSitsOut: !!room.winnerSitsOut, canConfigure: !!id && room.ownerId === id,
    id: room.id, revision: room.revision, reign: room.reign, turn: room.turn, phase: room.phase, deadline: ["dialogue", "feedback"].includes(room.phase) ? room.deadline : null, serverNow: now, turnKey: turnKey(room),
    speakerId: room.phase === "results" ? room.seats[room.speaker]?.id ?? null : null,
    thinking: room.phase === "evaluating",
    reply: room.phase === "results" ? (() => {
      const spoken = room.submissions[room.seats[room.speaker]?.id];
      return spoken && !spoken.pending && spoken.reply ? spoken.reply : null;
    })() : null,
    log: courtLog(room),
    seats: room.seats.map(s => {
      const submission = room.submissions[s.id];
      const visible = !["dialogue", "evaluating"].includes(room.phase);
      const line = visible && submission?.text.trim() ? submission.text : null;
      // History already includes a finished turn. The live turn is added only while it is still in dialogue.
      const scores = room.history.map(turn => turn[s.id]?.score ?? 0);
      if (room.phase === "results" && submission && !submission.pending) scores.push(submission.score);
      const scored = visible && !!line && !!submission && !submission.pending;
      return { id: s.id, name: s.name, kind: s.owner ? "human" as const : "npc" as const, total: s.total, liked: likedScore(scores), submitted: !!submission, lastScore: ["feedback", "reveal", "creating"].includes(room.phase) ? submission?.score ?? null : null, line, mark: visible && submission && !submission.pending ? markOutOfTen(submission.score) ?? 0 : null, spokenAt: scored && (room.phase !== "results" || room.seats.indexOf(s) === room.speaker) ? submission.at || null : null, note: scored ? submission.feedback : null };
    }),
    you: member ? { name: member.name, seatId: seat?.id ?? null, role: room.advisorId === id ? "advisor" : seat ? "suitor" : "spectator", submitted: !!own, dialogue } : null,
    creatorName: room.creator.name, winner: room.winner ? { seatId: room.winner.seatId, name: room.winner.name, total: room.winner.total } : null,
    prompt: questionFor(room.reign, room.turn).question, revealedPreference: ["reveal", "creating"].includes(room.phase) ? room.preferences.prompt : null,
    canCreate: room.phase === "creating" && !!id && room.winner?.memberId === id && !!member,
    creationPending: room.creationPending,
    humanCount: Object.values(room.members).filter(m => now - m.lastSeen <= PRESENCE_MS).length,
  };
}
